image: cypress/browsers:node12.18.0-chrome83-ff77

stages:
  - codeStyle
  - test
  - build
  - auto-tag
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  paths:
    - .npm/

before_script:
  - cp $NPMRC_PULL ~/.npmrc
  - npm ci --cache .npm --prefer-offline --ignore-scripts

codeStyle:
  stage: codeStyle
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - .npm/
    policy: pull
  script:
    - npm run lint
  rules:
    - changes:
        - "CHANGELOG.md"
      when: never

    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: never

    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "trigger"'
      when: always

unitTests:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - .npm/
    policy: pull
  script:
    - npm run ci-test
  rules:
    - changes:
        - "CHANGELOG.md"
      when: never

    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: never

    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "trigger"'

buildExampleApp:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - .npm/
    policy: pull
  script:
    - npm run build-example-app
  artifacts:
    paths:
      - ./dist
    expire_in: 1 hour
  rules:
    - changes:
        - "CHANGELOG.md"
      when: never

    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: never

    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "trigger"'

buildLibrary:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - .npm/
    policy: pull
  script:
    - npm run build-library
  artifacts:
    paths:
      - ./dist
    expire_in: 1 hour
  rules:
    - changes:
        - "CHANGELOG.md"
      when: never

    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: never

    - if: '$CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "trigger"'

auto-tag:
  image: 'registry.gitlab.ics.muni.cz:443/csirt-mu-devel/csirt-mu-devel-artifact-repository/docker-common-ci:v0.1.6'
  variables:
    GIT_STRATEGY: clone
  stage: auto-tag
  script:
    - source /app/export-tag-vars.sh VERSION.txt
    - echo $TAG_VERSION && echo $TAG_MESSAGE
    - /app/import-ssh-key.sh
    - /app/prepare-git.sh
    - /app/set-version-angular.sh
    - /app/create-changelog.sh
    - /app/tag-and-push.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - VERSION.txt

deploy:
  stage: deploy
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - .npm/
    policy: pull
  script:
    - cp $NPMRC_PULL ~/.npmrc
    - npm run ci-build-and-pack
    - cp $NPMRC_PUSH ~/.npmrc
    - npm run ci-publish-package
  only:
    - tags

